/**
 *
 */
export default Object.freeze({
  /**
   * Post related actions
   */
  POST_FETCH_POSTS: 'POST_ADD_POSTS',
  POST_POSTS_FETCHED: 'POST_POSTS_FETCHED',
  POST_FETCH_POST: 'POST_ADD_POST',
  POST_POST_FETCHED: 'POST_POST_FETCHED',
	POST_ADD_POST: 'POST_ADD_POST',
	POST_COMMENTS_FETCHED: 'POST_COMMENTS_FETCHED',
	POST_OPEN_POST_COMMENTS: 'POST_OPEN_POST_COMMENTS',
	POST_CLOSE_POST_COMMENTS: 'POST_CLOSE_POST_COMMENTS',
	POST_POST_ADDED: 'POST_POST_ADDED',
	POST_LIKE_POST: 'POST_LIKE_POST',
	POST_DISLIKE_POST: 'POST_DISLIKE_POST',
	POST_POST_DISLIKED: 'POST_POST_DISLIKED',
	POST_POST_DISLIKED_FAILED: 'POST_POST_DISLIKED_FAILED',

  /**
   * Profile related actions
   */
  NEWS_FETCH_DATA: 'NEWS_FETCH_DATA',
  NEWS_DATA_FETCHED: 'NEWS_DATA_FETCHED',

  /**
   * Profile related actions
   */
  PROFILE_FETCH_USER: 'PROFILE_FETCH_USER',
  PROFILE_USER_FETCHED: 'PROFILE_USER_FETCHED',

  /**
   * User related actions
   */
  USER_FETCH_USER: 'NETWORK_FETCH_USER',
  USER_USER_FETCHED: 'USER_USER_FETCHED',
  USER_ADD_USER: 'NETWORK_ADD_USER',
  USER_CLOSE_USER_MODAL: 'USER_CLOSE_USER_MODAL',

  /**
   * Network related actions
   */
  NETWORK_FETCH_USERS: 'NETWORK_FETCH_USERS',
  NETWORK_SEND_CONNECT_REQUEST_USER: 'NETWORK_SEND_CONNECT_REQUEST_USER',
});
