/**
 *
 */
export default Object.freeze({
  /**
   * Post related actions
   */
  POST_FETCH_POSTS: 'POST_ADD_POSTS',
  POST_FETCH_POST: 'POST_ADD_POST',
  POST_ADD_POST: 'POST_ADD_POST',
  POST_POST_ADDED: 'POST_POST_ADDED',
  POST_LIKE_POST: 'POST_LIKE_POST',

  /**
   * Profile related actions
   */
  PROFILE_FETCH_USER: 'PROFILE_FETCH_USER',
  PROFILE_USER_FETCHED: 'PROFILE_USER_FETCHED',

  /**
   * User related actions
   */
  USER_FETCH_USER: 'NETWORK_FETCH_USER',
  USER_USER_FETCHED: 'USER_USER_FETCHED',
  USER_ADD_USER: 'NETWORK_ADD_USER',
  USER_CLOSE_USER_MODAL: 'USER_CLOSE_USER_MODAL',

  /**
   * Network related actions
   */
  NETWORK_FETCH_USERS: 'NETWORK_FETCH_USERS',
  NETWORK_SEND_CONNECT_REQUEST_USER: 'NETWORK_SEND_CONNECT_REQUEST_USER',
});
